// Auto-generated by scripts/post-deploy-powerapps.ps1 - do not edit manually.
// Run the deploy script to regenerate for the target environment.
export const DEPLOY_ENV = {
  environmentId: 'dcd88fe8-d919-ee82-8313-8376a1e413f4',
  tenantId: '6fdb5200-3d0d-4a8a-b036-d3685e359adc',
  modelApps: [{"key":"core-crm","displayName":"CORE DEV","appModuleId":"88c024d9-9fd5-ec11-a7b5-002248ada475","iconUrl":"/icons/app-core-crm-dev.jpg"},{"key":"finance","displayName":"FINANCE DEV","appModuleId":"f09f4af5-f56c-ed11-81ac-0022483cb0d4","iconUrl":"/icons/app-finance-dev.png"}],
  canvasAppIds: {"change-management":"2a047e32-cfaa-40bd-a6f2-73ccd5cf8d06"},
  appIcons: {"enrollment-app":"/icons/app-enrollment-sm-dev.jpg","change-management":"/icons/app-code-management-sm-dev.jpg","farms":"/icons/app-farms-dev.jpg"},
  reminderTemplateGuids: {"nonPenalty":"8fdbc5e2-6a66-f111-ab0d-7ced8de0b3b0","finalDeadline":"63d870a8-6c66-f111-ab0d-7ced8de0b3b0","lateFinalDeadline":"8250c2b6-d095-f111-b8db-7ced8da50fa5"},
} as const;
