param(
  [Parameter(Mandatory = $true)]
  [ValidateSet('dev', 'test', 'prod')]
  [string]$Stage,

  [Parameter(Mandatory = $false)]
  [string]$ConfigPath = '.\scripts\powerapps-deploy.config.json',

  [Parameter(Mandatory = $false)]
  [string]$PowerConfigPath = '.\power.config.json',

  [Parameter(Mandatory = $false)]
  [string]$DeployEnvOutputPath = '.\src\constants\deployEnvConfig.ts',

  [Parameter(Mandatory = $false)]
  [switch]$SkipBuild,

  [Parameter(Mandatory = $false)]
  [switch]$SkipPush,

  [Parameter(Mandatory = $false)]
  [switch]$AllowPlaceholders
)

# --------------------------------------------------------------------------
# Benefit App deployment script.
#
# Rewrites `power.config.json` and `src/constants/deployEnvConfig.ts` for the
# target stage (dev / test / prod) using values from `powerapps-deploy.config.json`,
# then optionally builds and pushes via the Power Apps CLI (`pa`).
#
# Usage:
#   .\scripts\post-deploy-powerapps.ps1 -Stage test
#   .\scripts\post-deploy-powerapps.ps1 -Stage dev -SkipPush
#
# The `pa` binary is provided by @microsoft/power-apps-cli; if not on PATH we
# fall back to `npx pa`.
# --------------------------------------------------------------------------

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

function Assert-NotPlaceholder {
  param([string]$Value, [string]$Name)
  if ([string]::IsNullOrWhiteSpace($Value)) {
    throw "Missing required config property '$Name'."
  }
  if ($Value -match '^replace-with-') {
    if ($AllowPlaceholders.IsPresent) {
      Write-Host "  Warning: '$Name' is still a placeholder ('$Value'). Continuing because -AllowPlaceholders was set." -ForegroundColor Yellow
      return
    }
    throw "Config property '$Name' still has a placeholder value: '$Value'. Fill it in (or pass -AllowPlaceholders) before deploying."
  }
}

function Invoke-Pa {
  param([string[]]$Arguments, [string]$Description)

  Write-Host "`n==> $Description" -ForegroundColor Cyan

  $paCmd = Get-Command 'pa' -ErrorAction SilentlyContinue
  if ($paCmd) {
    Write-Host "    pa $($Arguments -join ' ')" -ForegroundColor DarkGray
    & pa @Arguments
  } else {
    Write-Host "    npx pa $($Arguments -join ' ')" -ForegroundColor DarkGray
    & npx pa @Arguments
  }

  if ($LASTEXITCODE -ne 0) {
    throw "pa command failed with exit code ${LASTEXITCODE}: pa $($Arguments -join ' ')"
  }
}

# --- Load config -----------------------------------------------------------

if (-not (Test-Path -LiteralPath $ConfigPath)) {
  throw "Cannot find deploy config at '$ConfigPath'."
}
if (-not (Test-Path -LiteralPath $PowerConfigPath)) {
  throw "Cannot find power config at '$PowerConfigPath'."
}

$deployConfig = Get-Content -LiteralPath $ConfigPath -Raw | ConvertFrom-Json
$powerConfig  = Get-Content -LiteralPath $PowerConfigPath -Raw | ConvertFrom-Json

if ($null -eq $deployConfig.environments.$Stage) {
  throw "Stage '$Stage' does not exist in '$ConfigPath'."
}

$target = $deployConfig.environments.$Stage
$tenantId = [string]$deployConfig.tenantId
$dataverseRefId = [string]$deployConfig.dataverseReferenceId

Assert-NotPlaceholder -Value $tenantId -Name 'tenantId'
Assert-NotPlaceholder -Value $dataverseRefId -Name 'dataverseReferenceId'
Assert-NotPlaceholder -Value ([string]$target.environmentId)         -Name "environments.$Stage.environmentId"
Assert-NotPlaceholder -Value ([string]$target.dataverseInstanceUrl)  -Name "environments.$Stage.dataverseInstanceUrl"
Assert-NotPlaceholder -Value ([string]$target.dataverseConnectionId) -Name "environments.$Stage.dataverseConnectionId"

$environmentId = [string]$target.environmentId
$dataverseInstanceUrl = [string]$target.dataverseInstanceUrl
$dataverseConnectionId = [string]$target.dataverseConnectionId

Write-Host "`n=== Deploying Benefit App to stage: $Stage ===" -ForegroundColor Green
Write-Host "  environmentId       : $environmentId"
Write-Host "  dataverseInstanceUrl: $dataverseInstanceUrl"

# --- Rewrite src/constants/deployEnvConfig.ts ------------------------------

$modelAppsJson = ($target.modelApps | ConvertTo-Json -Compress -Depth 10)
$canvasAppIdsJson = ($target.canvasAppIds | ConvertTo-Json -Compress -Depth 10)

$deployEnvContent = @"
// Auto-generated by scripts/post-deploy-powerapps.ps1 - do not edit manually.
// Run the deploy script (.\scripts\post-deploy-powerapps.ps1 -Stage <stage>) to regenerate.
export const DEPLOY_ENV = {
  stage: '$Stage',
  environmentId: '$environmentId',
  tenantId: '$tenantId',
  modelApps: $modelAppsJson,
  canvasAppIds: $canvasAppIdsJson,
} as const;
"@

$deployEnvOutputDir = Split-Path -Parent $DeployEnvOutputPath
if (-not (Test-Path -LiteralPath $deployEnvOutputDir)) {
  New-Item -ItemType Directory -Path $deployEnvOutputDir -Force | Out-Null
}
Set-Content -LiteralPath $DeployEnvOutputPath -Value $deployEnvContent -NoNewline
Write-Host "`n==> Wrote $DeployEnvOutputPath" -ForegroundColor Cyan

# --- Rewrite power.config.json ---------------------------------------------

$powerConfig.environmentId = $environmentId

# App ID: leave null if placeholder, otherwise set it.
$appId = [string]$target.appId
if (-not [string]::IsNullOrWhiteSpace($appId) -and -not ($appId -match '^replace-with-')) {
  $powerConfig.appId = $appId
}

# Dataverse connection reference
if ($null -eq $powerConfig.connectionReferences) {
  $powerConfig | Add-Member -MemberType NoteProperty -Name connectionReferences -Value ([PSCustomObject]@{})
}
$sharedPath = "/providers/Microsoft.PowerApps/apis/shared_commondataserviceforapps/connections/$dataverseConnectionId"
$dataverseRef = [PSCustomObject]@{
  id                 = '/providers/Microsoft.PowerApps/apis/shared_commondataserviceforapps'
  displayName        = 'Microsoft Dataverse'
  dataSources        = @('commondataserviceforapps')
  authenticationType = 'ServicePrincipalOauth'
  sharedConnectionId = $sharedPath
  dataSets           = [PSCustomObject]@{}
}
# Rebuild connectionReferences to guarantee the Dataverse reference is present with the right key.
$newConnectionRefs = [PSCustomObject]@{}
Add-Member -InputObject $newConnectionRefs -MemberType NoteProperty -Name $dataverseRefId -Value $dataverseRef
foreach ($existing in $powerConfig.connectionReferences.PSObject.Properties) {
  if ($existing.Name -ne $dataverseRefId -and $existing.Value.id -ne '/providers/Microsoft.PowerApps/apis/shared_commondataserviceforapps') {
    Add-Member -InputObject $newConnectionRefs -MemberType NoteProperty -Name $existing.Name -Value $existing.Value
  }
}
$powerConfig.connectionReferences = $newConnectionRefs

# Database references (Dataverse CDS)
if ($null -eq $powerConfig.databaseReferences -or $null -eq $powerConfig.databaseReferences.'default.cds') {
  throw "power.config.json is missing databaseReferences.'default.cds'. Run 'pa app add data-source' first."
}

# Ensure required fields on default.cds exist and are set to the target values.
$cds = $powerConfig.databaseReferences.'default.cds'
function Set-OrAddProperty {
  param([Parameter(Mandatory)]$Object, [Parameter(Mandatory)][string]$Name, [Parameter(Mandatory)]$Value)
  if ($null -ne ($Object | Get-Member -Name $Name -MemberType NoteProperty -ErrorAction SilentlyContinue)) {
    $Object.$Name = $Value
  } else {
    Add-Member -InputObject $Object -MemberType NoteProperty -Name $Name -Value $Value
  }
}
Set-OrAddProperty -Object $cds -Name 'state'         -Value 'Configured'
Set-OrAddProperty -Object $cds -Name 'instanceUrl'   -Value $dataverseInstanceUrl
Set-OrAddProperty -Object $cds -Name 'webApiVersion' -Value 'v9.0'
Set-OrAddProperty -Object $cds -Name 'version'       -Value 'v9.0'
Set-OrAddProperty -Object $cds -Name 'environmentVariableName' -Value ''

$powerConfig | ConvertTo-Json -Depth 30 | Set-Content -LiteralPath $PowerConfigPath
Write-Host "==> Wrote $PowerConfigPath" -ForegroundColor Cyan

# --- Build -----------------------------------------------------------------

if (-not $SkipBuild.IsPresent) {
  Write-Host "`n==> Building app (npm run build)" -ForegroundColor Cyan
  & npm run build
  if ($LASTEXITCODE -ne 0) {
    throw "npm run build failed with exit code $LASTEXITCODE"
  }
}

# --- Push ------------------------------------------------------------------
# NOTE: Push to the Power Platform environment is intentionally disabled for now.
# The app has not been published yet. When you're ready to enable auto-push,
# uncomment the block below and remove this note.
#
# if (-not $SkipPush.IsPresent) {
#   $env:PA_CLI_ENVIRONMENT_ID = $environmentId
#   Write-Host "`n  Set PA_CLI_ENVIRONMENT_ID=$environmentId for pa app commands." -ForegroundColor DarkGray
#   Invoke-Pa -Arguments @('app', 'push', '--non-interactive') -Description "Push app to $Stage environment"
# }

Write-Host "`n(Push step is currently commented out - files rewritten only. Run 'npx pa app push' manually when ready.)" -ForegroundColor Yellow
Write-Host "`n=== Deployment to $Stage complete ===" -ForegroundColor Green
