import { useCallback, useEffect, useState } from 'react';
import { Globe, Layers, LayoutDashboard, X } from 'lucide-react';
import { Vsi_armsconfigurationsService } from '../generated/services/Vsi_armsconfigurationsService';
import { getCoreConfig } from '../hooks/useEnrolmentData';
import { DEPLOY_ENV } from '../constants/deployEnvConfig';
import { ICON_ASSET_URLS } from '../assets/iconAssets';
import '../styles/app-switcher.css';

// ── Static app config ────────────────────────────────────────────────────────
// Model app names/IDs and canvas app IDs are all environment-specific.
// They come from deployEnvConfig.ts, regenerated by post-deploy-powerapps.ps1.
type ModelAppConfig = { key: string; displayName: string; appModuleId: string; iconUrl?: string };
const MODEL_APPS = DEPLOY_ENV.modelApps as unknown as ModelAppConfig[];

// Canvas app IDs are environment-specific; they come from deployEnvConfig.ts which is
// regenerated by post-deploy-powerapps.ps1 for each target environment.
const CANVAS_APPS = [
  { key: 'change-management', displayName: 'Change Management' },
] as const;

function resolveCanvasUrl(key: string): string | null {
  const ids = DEPLOY_ENV.canvasAppIds as Record<string, string>;
  const appId = ids[key];
  if (!appId || appId.startsWith('replace-with-')) return null;
  return `https://apps.powerapps.com/play/e/${DEPLOY_ENV.environmentId}/a/${appId}?tenantId=${DEPLOY_ENV.tenantId}&hidenavbar=true`;
}

type AppType = 'model' | 'canvas' | 'code' | 'external';

interface ResolvedApp {
  key: string;
  displayName: string;
  type: AppType;
  url: string | null;
  isCurrent: boolean;
}

// ── URL helpers ──────────────────────────────────────────────────────────────
function normalizeOrgUrl(url: string | null | undefined): string | null {
  const trimmed = url?.trim();
  if (!trimmed) return null;
  return trimmed.replace(/\/main\.aspx.*$/i, '').replace(/\/?$/, '/');
}

function isActiveConfig(value: unknown): boolean {
  if (value === true || value === 1) return true;
  if (typeof value === 'string') {
    const n = value.trim().toLowerCase();
    return n === 'true' || n === '1' || n === 'yes';
  }
  return false;
}

async function resolveFarmsUrl(): Promise<string | null> {
  // Fetch all fields (no select) and try all known prefix/case variants,
  // matching the same logic used by EnrolmentCalculationPage.getFarmsLegacyBaseUrl().
  const result = await Vsi_armsconfigurationsService.getAll({
    maxPageSize: 50,
    orderBy: ['modifiedon desc'],
  });
  const rows = result.data ?? [];
  for (const row of rows) {
    const r = row as unknown as Record<string, unknown>;
    const url = (
      (typeof r['cr2a9_FARMSURLNEW'] === 'string' && r['cr2a9_FARMSURLNEW'].trim()) ||
      (typeof r['cr2a9_farmsurlnew'] === 'string' && r['cr2a9_farmsurlnew'].trim()) ||
      (typeof r['cr4dd_FARMSURLNEW'] === 'string' && r['cr4dd_FARMSURLNEW'].trim()) ||
      (typeof r['cr4dd_farmsurlnew'] === 'string' && r['cr4dd_farmsurlnew'].trim())
    ) || null;
    if (url) return url;
  }
  return null;
}

async function resolveOrgUrl(): Promise<string | null> {
  const cached = getCoreConfig().dataverseOrgUrl;
  if (cached) return cached;

  const result = await Vsi_armsconfigurationsService.getAll({
    maxPageSize: 50,
    select: ['vsi_activeconfiguration', 'vsi_coreenvironmenturl'],
    orderBy: ['modifiedon desc'],
  });
  const rows = result.data ?? [];
  const active = rows.find(r =>
    isActiveConfig((r as unknown as Record<string, unknown>).vsi_activeconfiguration) &&
    r.vsi_coreenvironmenturl?.trim()
  );
  const row = active ?? rows.find(r => r.vsi_coreenvironmenturl?.trim());
  return normalizeOrgUrl(row?.vsi_coreenvironmenturl);
}

// ── Icons ────────────────────────────────────────────────────────────────────
// Icons are looked up via ICON_ASSET_URLS so Vite processes them into dist/assets/
// (ensuring npx power-apps push includes them in the deployed bundle).
function resolveIconUrl(url: string): string {
  return ICON_ASSET_URLS[url] ?? `${import.meta.env.BASE_URL}${url.replace(/^\//, '')}`;
}
function EnrolmentSvgIcon() {
  return (
    <svg viewBox="0 0 150 100" aria-hidden="true" focusable="false" className="app-card-svg-icon">
      <path d="M4 12H72L88 30H22V43H56V57H22V78H72V94H4V12Z" fill="currentColor" />
      <path d="M71 12H91L137 94H117L71 30V12Z" fill="currentColor" />
      <path d="M124 24H146V94H124V24Z" fill="currentColor" />
      <path d="M74 39L90 62V94H74V39Z" fill="currentColor" />
    </svg>
  );
}

/**
 * CORE CRM app icon.
 * Loaded from iconUrl in deployEnvConfig (e.g. /icons/app-core-crm.png).
 * Falls back to a placeholder if the file is not yet added.
 */
function AppIconCoreCrm() {
  const cfg = MODEL_APPS.find(a => a.key === 'core-crm');
  if (cfg?.iconUrl) {
    return <img src={resolveIconUrl(cfg.iconUrl)} alt="" className="app-card-icon-img" />;
  }
  return (
    <svg viewBox="0 0 100 100" aria-hidden="true" focusable="false" className="app-card-svg-icon">
      <rect x="10" y="10" width="80" height="80" rx="12" fill="currentColor" opacity="0.35" />
      <text x="50" y="62" textAnchor="middle" fill="currentColor" fontSize="32" fontWeight="bold">C</text>
    </svg>
  );
}

/**
 * FINANCE app icon.
 * Loaded from iconUrl in deployEnvConfig (e.g. /icons/app-finance.png).
 * Falls back to a placeholder if the file is not yet added.
 */
function AppIconFinance() {
  const cfg = MODEL_APPS.find(a => a.key === 'finance');
  if (cfg?.iconUrl) {
    return <img src={resolveIconUrl(cfg.iconUrl)} alt="" className="app-card-icon-img" />;
  }
  return (
    <svg viewBox="0 0 100 100" aria-hidden="true" focusable="false" className="app-card-svg-icon">
      <rect x="10" y="10" width="80" height="80" rx="12" fill="currentColor" opacity="0.35" />
      <text x="50" y="62" textAnchor="middle" fill="currentColor" fontSize="32" fontWeight="bold">F</text>
    </svg>
  );
}

function AppIcon({ type, appKey }: { type: AppType; appKey: string }) {
  if (appKey === 'core-crm') return <AppIconCoreCrm />;
  if (appKey === 'finance') return <AppIconFinance />;
  const appIcons = DEPLOY_ENV.appIcons as Record<string, string>;
  const iconUrl = appIcons[appKey];
  if (iconUrl) return <img src={resolveIconUrl(iconUrl)} alt="" className="app-card-icon-img" />;
  if (type === 'code') return <EnrolmentSvgIcon />;
  if (type === 'canvas') return <Layers size={36} />;
  if (type === 'external') return <Globe size={36} />;
  return <LayoutDashboard size={36} />;
}

// ── Card ─────────────────────────────────────────────────────────────────────
function AppCard({ app }: { app: ResolvedApp }) {
  const typeLabelMap: Record<AppType, string> = {
    model:    'UNIFIED INTERFACE',
    canvas:   'CANVAS',
    code:     'CODE APP',
    external: 'WEB APP',
  };

  const content = (
    <>
      <div className="app-card-icon-area">
        <AppIcon type={app.type} appKey={app.key} />
      </div>
      <div className="app-card-body">
        <span className="app-card-name">{app.displayName}</span>
        <span className={`app-card-badge app-card-badge--${app.type}`}>
          {typeLabelMap[app.type]}
        </span>
      </div>
    </>
  );

  const cls = `app-card${app.isCurrent ? ' app-card--current' : ''}`;

  if (app.url && !app.isCurrent) {
    return (
      <a href={app.url} target="_blank" rel="noopener noreferrer" className={cls} title={`Open ${app.displayName}`}>
        {content}
      </a>
    );
  }
  return <div className={cls}>{content}</div>;
}

// ── Main component ───────────────────────────────────────────────────────────
export function AppSwitcher({ onClose }: { onClose: () => void }) {
  const [apps, setApps] = useState<ResolvedApp[]>(() => [
    ...MODEL_APPS.map(c => ({
      key: c.key,
      displayName: c.displayName,
      type: 'model' as AppType,
      url: null,
      isCurrent: false,
    })),
    { key: 'enrollment-app', displayName: 'Enrolment App', type: 'code' as AppType, url: null, isCurrent: true },
    ...CANVAS_APPS.map(c => ({ key: c.key, displayName: c.displayName, type: 'canvas' as AppType, url: resolveCanvasUrl(c.key), isCurrent: false })),
    { key: 'farms', displayName: 'FARMS', type: 'external' as AppType, url: null, isCurrent: false },
  ]);

  useEffect(() => {
    let cancelled = false;

    async function resolve() {
      // Resolve model-driven URLs from org URL + known app module IDs.
      // Note: appmodules/canvasapps/webresourceset are blocked by the Dataverse connector
      // so canvas URLs are hardcoded in CANVAS_APPS config above.
      const orgUrl = await resolveOrgUrl().catch(() => null);
      if (!cancelled && orgUrl) {
        setApps(prev => prev.map(app => {
          const cfg = MODEL_APPS.find(c => c.key === app.key);
          if (cfg) return { ...app, url: `${orgUrl}main.aspx?appid=${cfg.appModuleId}` };
          return app;
        }));
      }

      // Resolve FARMS URL from Dataverse config
      const farmsUrl = await resolveFarmsUrl().catch(() => null);
      if (!cancelled && farmsUrl) {
        setApps(prev => prev.map(app =>
          app.key === 'farms' ? { ...app, url: farmsUrl } : app
        ));
      }
    }

    void resolve();
    return () => { cancelled = true; };
  }, []);

  const handleClose = useCallback(() => onClose(), [onClose]);

  // Close on Escape
  useEffect(() => {
    const handler = (e: KeyboardEvent) => { if (e.key === 'Escape') handleClose(); };
    window.addEventListener('keydown', handler);
    return () => window.removeEventListener('keydown', handler);
  }, [handleClose]);

  return (
    <div
      className="app-switcher-backdrop"
      onClick={handleClose}
      role="dialog"
      aria-modal="true"
      aria-label="App switcher"
    >
      <div className="app-switcher-panel" onClick={e => e.stopPropagation()}>
        <div className="app-switcher-header">
          <h2 className="app-switcher-title">Apps</h2>
          <button
            className="app-switcher-close"
            onClick={handleClose}
            aria-label="Close app switcher"
            type="button"
          >
            <X size={20} />
          </button>
        </div>
        <div className="app-switcher-grid">
          {apps.map(app => (
            <AppCard key={app.key} app={app} />
          ))}
        </div>
      </div>
    </div>
  );
}
